
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 03 13:01:47 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 10;
  public static final int CONST = 5;
  public static final int YIELD = 54;
  public static final int LESSE = 42;
  public static final int GRT = 38;
  public static final int NUMCONST = 32;
  public static final int QUESTIONMARK = 15;
  public static final int CASE = 46;
  public static final int NOTEQUAL = 49;
  public static final int CONTINUE = 52;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int LESS = 43;
  public static final int MINUS = 17;
  public static final int RPAREN = 13;
  public static final int AND = 40;
  public static final int OR = 53;
  public static final int COMMA = 7;
  public static final int ORD = 29;
  public static final int CLASS = 9;
  public static final int INC = 19;
  public static final int DIV = 22;
  public static final int PLUS = 18;
  public static final int IF = 36;
  public static final int ASSIGN = 8;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 51;
  public static final int GRTE = 45;
  public static final int EQUAL = 41;
  public static final int RBRACKET = 11;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int JUMP = 55;
  public static final int MOD = 23;
  public static final int BREAK = 47;
  public static final int IDENT = 31;
  public static final int VOID = 14;
  public static final int SWITCH = 39;
  public static final int COLON = 16;
  public static final int ELSE = 35;
  public static final int LBRACE = 3;
  public static final int ENUM = 44;
  public static final int READ = 26;
  public static final int WHILE = 48;
  public static final int CHARCONST = 34;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 33;
  public static final int EXTENDS = 24;
  public static final int PROG = 2;
  public static final int LEN = 30;
  public static final int CHR = 28;
  public static final int DEC = 20;
  public static final int DO = 50;
  public static final int PRINT = 27;
}

